import { describe, expect, it } from "vitest";

import * as sdk from "./index.js";

describe("public package surface", () => {
  it("exports only the deliberate runtime API", () => {
    expect(Object.keys(sdk).sort()).toStrictEqual([
      "AccountType",
      "AcquiringPaymentScheme",
      "AcquiringStatementStatus",
      "CashbackType",
      "DiscountMode",
      "DiscountType",
      "FiscalCheckStatus",
      "FiscalCheckType",
      "FiscalizationSource",
      "InvoiceCancellationStatus",
      "InvoicePaymentMethod",
      "InvoicePaymentSystem",
      "InvoicePaymentType",
      "InvoiceStatus",
      "InvoiceWalletStatus",
      "MonobankAcquiringClient",
      "MonobankApiError",
      "MonobankNetworkError",
      "MonobankPersonalClient",
      "MonobankPublicClient",
      "MonobankResponseValidationError",
      "MonobankValidationError",
      "accountSchema",
      "acquiringStatementCancellationSchema",
      "acquiringStatementItemSchema",
      "acquiringStatementSchema",
      "acquiringWebhookPublicKeySchema",
      "bankSyncSchema",
      "cancelInvoiceResponseSchema",
      "clientInfoSchema",
      "currencyRateSchema",
      "currencyRatesSchema",
      "finalizeInvoiceResponseSchema",
      "invoiceFiscalChecksSchema",
      "invoiceStatusSchema",
      "jarSchema",
      "managedAccountSchema",
      "managedClientSchema",
      "merchantDetailsSchema",
      "newInvoiceSchema",
      "parsePersonalWebhookEvent",
      "personalWebhookEventSchema",
      "receiptSchema",
      "statementItemSchema",
      "statementItemsSchema",
      "verifyAcquiringWebhookSignature",
    ]);
  });
});
